name: Get Check Run ID and Trigger Action

on: 
  issue_comment:
    types: [created]

jobs:
  get_check_run_id:
    runs-on: ubuntu-latest

    steps:
    - name: Get Check Run ID
      id: check_run_id
      run: |
        check_runs=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}/check-runs")
        check_run_id=$(echo $check_runs | jq -r '.check_runs[0].id')
        echo "::set-output name=check_run_id::${check_run_id}"

    - name: Use Check Run ID
      run: |
        check_run_id="${{ steps.check_run_id.outputs.check_run_id }}"
        echo "Check Run ID: $check_run_id"
