name: Check Latest Commit Status

on:
  issue_comment:
    types: [created]

jobs:
  check-commit-status:
    runs-on: ubuntu-latest

    steps:
    - name: "Get branch name"
      uses: xt0rted/pull-request-comment-branch@29fe0354c01b30fb3de76f193ab33abf8fe5ddb0 #1.2.0
      id: comment-branch
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Get Latest Commit SHA
      id: commit_sha
      run: |
        BRANCH_NAME=${{ steps.comment-branch.outputs.branch_name }}
        echo "COMMIT_SHA=$(git rev-parse BRANCH_NAME)" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Check Suites
      id: check_suites
      run: |
        CHECK_SUITES_RESPONSE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ env.COMMIT_SHA }}/check-suites")
        CONCLUSIONS=($(echo $CHECK_SUITES_RESPONSE | jq -r '.check_suites[].conclusion'))
        echo "Conclusions: ${CONCLUSIONS[*]}"
        for CONCLUSION in "${CONCLUSIONS[@]}"; do
          if [ "$CONCLUSION" == "failure" ]; then
            echo "There is a failed check suite."
            exit 1
          fi
        done
        echo "No failed check suites."
