name: Get and Echo Check Run ID

on:
  issue_comment:
    types: [created]

jobs:
  get_check_run_id:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Current Branch
      id: get-branch
      run: |
        current_branch=$(git symbolic-ref --short HEAD)
        echo "::set-output name=branch::$current_branch"

    - name: Get Check Run ID
      id: get-staging-test-check-runs-id
      uses: actions/github-script@v2
      with:
        script: |
          const list = await github.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: ${{ steps.get-branch.outputs.branch }} # 現在のブランチを使用
            check_name: 'staging-test',
            filter: 'latest'
          });
          return list.data.check_runs[0].id;

    - name: Echo Check Run ID
      run: |
        check_run_id="${{ steps.get-staging-test-check-runs-id.outputs.result }}"
        echo "Check Run ID: $check_run_id"
