name: Check Latest Commit Status

on:
  issue_comment:
    types: [created]
jobs:
  check-commit-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Commit SHA
      run: echo "COMMIT_SHA=$(git log -1 --format='%H')" >> $GITHUB_ENV

    - name: Get Check Suites
      run: |
        CHECK_SUITES_RESPONSE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ env.COMMIT_SHA }}/check-suites")
        echo "Check Suites Response: $CHECK_SUITES_RESPONSE"
        CONCLUSION=$(echo $CHECK_SUITES_RESPONSE | jq -r '.check_suites[] | select(.conclusion == "failure") | .conclusion')
        echo "Conclusion: $CONCLUSION"
        if [ -n "$CONCLUSION" ]; then
          echo "There are failed check suites."
        else
          echo "No failed check suites."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Tokenを使用してAPIにアクセス
        COMMIT_SHA: ${{ env.COMMIT_SHA }}  # コミットSHAを使用

