name: Check Latest Commit Status

on:
  issue_comment:
    types: [created]
jobs:
  check-commit-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Commit SHA
      run: echo "COMMIT_SHA=$(git log -1 --format='%H')" >> $GITHUB_ENV

    - name: Get Check Suites
      run: |
        CHECK_SUITES_RESPONSE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ env.COMMIT_SHA }}/check-suites")
        CONCLUSIONS=($(echo $CHECK_SUITES_RESPONSE | jq -r '.check_suites[].conclusion'))
        echo "Conclusions: ${CONCLUSIONS[*]}"
        for CONCLUSION in "${CONCLUSIONS[@]}"; do
          if [ "$CONCLUSION" == "failure" ]; then
            echo "There is a failed check suite."
            exit 1
          fi
        done
        echo "No failed check suites."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Tokenを使用してAPIにアクセス
        COMMIT_SHA: ${{ env.COMMIT_SHA }}  # コミットSHAを使用
