name: Slack Notification

on: 
  issue_comment:
    types: [created, edited]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  slackNotification:
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') && 
        startsWith(github.event.comment.body, '/review') &&
        github.event.pull_request.mergeable == true
    name: Slack-Notification
    runs-on: ubuntu-latest

    steps:
    #-- Gitリポジトリの内容を取得 --#
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.get_branch.outputs.branch }}

    #-- Pull RequestのURL取得 --#
    - name: Get URL
      id: get_url
      run: |
        html_url="${{ github.event.comment.html_url }}"
        url_without_anchor="$(echo $html_url | cut -d'#' -f1)"
        echo "::set-output name=html_url::$html_url"
        echo "::set-output name=url_without_anchor::$url_without_anchor"

    #-- Slack通知 --#
    # 成功
    - name: Slack Notification on Success
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_TITLE: Message
        SLACK_LINK_NAMES: true # メッセージ内でのメンションを有効にする
        SLACK_MESSAGE: |
          @メンショングループを指定する
          レビュー依頼が届きました！
          ${{ steps.get_url.outputs.url_without_anchor }}
        MSG_MINIMAL: true # メッセージだけを通知文にする
        SLACK_USERNAME: レビュー依頼Bot
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    
    - name: Comments
      run: |
        echo "Slackにコメントを投稿しました。 (${{ github.event.comment.body }})"
      
    # 失敗
  addCommentIfSkipped:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check if Workflow was Skipped
      id: check_workflow
      run: |
        SKIPPED=$(jq -r .workflow_run.conclusion <<< "${{ github.event.workflow_run }}")
        echo "::set-output name=SKIPPED::$SKIPPED"
    - name: Add Comment if Skipped
      if: ${{ steps.check_workflow.outputs.SKIPPED == 'skipped' }}
      run: |
        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        COMMENT_BODY="ジョブはスキップされました"
        echo "::set-env name=COMMENT_BODY::$COMMENT_BODY"
        echo "Creating comment..."
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
          -d "{\"body\": \"$COMMENT_BODY\"}"
