name: Slack Notification

on: 
  issue_comment:
    types: [created]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  START_review_COMMENT: '/review'

jobs:
  notification:
    name: 'Notification'
    runs-on: ubuntu-latest
    steps:
      # 「/review」とユーザーがコメントした場合
    - name: 'Start review'
      if: github.event.issue.state == 'open' && github.event.issue.pull_request != null && github.event.comment.body == env.START_review_COMMENT
      run: |
        curl -X POST \
          --data-urlencode 'payload={
            "attachments": [
              {
                "color": "#FFC0CB",
                "blocks": [
                  {
                    "type": "section",
                    "block_id": "sectionBlockOnlyMrkdwn",
                    "text": {
                      "type": "mrkdwn",
                      "text": "<@${{secrets.SLACK_USER_ID}}>\n レビュー依頼が届きました！ご確認をお願いします:bow:"
                    }
                  },
                  {
                    "type": "context",
                    "elements": [
                      {
                        "type": "image",
                        "image_url": "${{ github.user.avatar_url }}",
                        "alt_text": "github_icon"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "${{ github.actor }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "block_id": "sectionBlockOnlyMrkdwna",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*タイトル*\n ${{ github.event.issue.title }}"
                    }
                  },
                  {
                    "type": "section",
                    "block_id": "sectionBlockOnlyMrkdwnb",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*URL*\n https://github.com/${{ github.repository }}/pull/${{ github.event.issue.number }}"
                    }
                  }
                ]
              }
            ]
          }' \
        ${{ secrets.SLACK_WEBHOOK }}
      
  addCommentIfSkipped:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check if Workflow was Skipped or Failed
      id: check_workflow
      run: |
        CONCLUSION=$(jq -r '.conclusion' <<< "${{ github.event.workflow_run }}")
        SKIPPED=$(jq -r '.conclusion == "skipped" || .conclusion == "failure"' <<< "${{ github.event.workflow_run }}")
        echo "SKIPPED=${SKIPPED}" >> $GITHUB_ENV
      continue-on-error: true

    - name: Post Comment
      if: env.SKIPPED == 'true'
      uses: actions/github-script@v3
      env:
        MESSAGE: |
          レビュー依頼がスキップまたは失敗しました。
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.MESSAGE
          })
