name: Slack Notification

on: 
  issue_comment:
    types: [created, edited]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  slackNotification:
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') && 
        startsWith(github.event.comment.body, '/review')
    name: Slack-Notification
    runs-on: ubuntu-latest

    steps:
    #-- Gitリポジトリの内容を取得 --#
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.get_branch.outputs.branch }}

    #-- Slack通知 --#
    # 成功
    - name: Slack Notification on Success
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_TITLE: Message
        SLACK_LINK_NAMES: true # メッセージ内でのメンションを有効にする
        SLACK_MESSAGE: |
          @メンショングループを指定する
          レビュー依頼が届きました！
          ${{ github.event.comment.html_url }}
        MSG_MINIMAL: true # メッセージだけを通知文にする
        SLACK_USERNAME: レビュー依頼Bot
        SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    # 失敗
    #-- 何もしない --#
